version: '3'
services:
    db57:
        env_file: .env
        build: ./db
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${USER_NAME}
            MYSQL_PASSWORD: ${USER_PASS}
            MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
            TZ: "Asia/Tokyo"
        ports:
            - "3306:3306"
    app57:
        build: ./app/
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true
